Repository srin91297/senate-voting-application, pull requests merged in 2019-10, with the labels that each got.

#12 Mongodb login
  .idea/.gitignore
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/senate-voting-application.iml
  .idea/vcs.xml
  .vs/ProjectSettings.json
  .vs/VSWorkspaceState.json
  .vs/launch.vs.json
  .vs/senate-voting-application/config/applicationhost.config
  .vs/senate-voting-application/v16/.suo
  .vs/slnx.sqlite
  APP/app.py
  APP/flaskr.egg-info/PKG-INFO
  APP/flaskr.egg-info/SOURCES.txt
  APP/flaskr.egg-info/dependency_links.txt
  APP/flaskr.egg-info/not-zip-safe
  APP/flaskr.egg-info/requires.txt
  APP/flaskr.egg-info/top_level.txt
  APP/setup.py
  APP/templates/index.html
  APP/templates/layout.html
  APP/templates/register.html
Labels: pull request

#15 #14 created structure
  APP/__pycache__/app.cpython-37.pyc
  APP/__pycache__/controller_index.cpython-37.pyc
  APP/__pycache__/controller_login.cpython-37.pyc
  APP/__pycache__/controller_register.cpython-37.pyc
  APP/app.py
  APP/controller_index.py
  APP/controller_login.py
  APP/controller_register.py
  APP/models/candidate.py
  APP/models/party.py
  APP/models/user.py
  APP/models/vote.py
  APP/templates/index.html
  APP/templates/login.html
Labels: pull request

#17 #7 ssv
  APP/.gitignore
  APP/controller_login.py
  APP/controller_register.py
Labels: pull request

#19 Task 2 clean up
  APP/README.md
  APP/setup.py
  APP/templates/index.html
Labels: 1, enhancement

#32 adding admin role
  APP/app.py
  APP/controller_admindashboard.py
  APP/controller_login.py
  APP/templates/admindashboard.html
  APP/templates/index.html
Labels: login page

#35 separating the admin and voter login databases
  ADMIN/app.py
  ADMIN/controller_login.py
  ADMIN/controller_register.py
  VOTER/controller_login.py
Labels: pull request

#43 #27 Candidates can be viewed
  ADMIN/app.py
  ADMIN/controller_admindashboard.py
  ADMIN/controller_login.py
  ADMIN/controller_logout.py
  ADMIN/controller_register.py
  ADMIN/models/candidate.py
  ADMIN/models/party.py
  ADMIN/modeltest.py
  ADMIN/templates/admindashboard.html
  ADMIN/templates/candidates.html
  ADMIN/templates/layout.html
Labels: pull request

#45 #28 #29 crud operations for candidates works
  ADMIN/app.py
  ADMIN/controller_admindashboard.py
  ADMIN/controller_index.py
  ADMIN/controller_login.py
  ADMIN/controller_logout.py
  ADMIN/controller_register.py
  ADMIN/models/candidate.py
  ADMIN/templates/candidates.html
Labels: pull request
